### ISSUE TITLE
App does not maintain state when moving across tabs

### ISSUE THREAD

**Issue by AetherPrior** [Dryft-bits/ChronoFactorem#52]

**Comment by Aviral14** [comment]
Is this functionality even intended? We can always prompt the user to save the time table before switching tabs.

**Comment by Kushagra-0801** [comment]
Lets try to save state if it isn't too much work

**Comment by Kushagra-0801** [comment]
its good UX that way

**Comment by Aviral14** [comment]
This will be discussed only when #34 is sorted.Because if we decide to use different routes for different tabs then this functionality won't make much sense.

**Comment by VikramjeetD** [comment]
Solved in #62
