### ISSUE TITLE
Css / Material UI affects components unpredictably

### ISSUE THREAD

**Issue by VikramjeetD** [Dryft-bits/ChronoFactorem#63]
Some effects (Eg: the sea green button highlight on landing page on clicking) were unintentional. The color being same as that of the buttons in the create timetable page indicates some interference with material ui. 

@HarshvardhanJha1 Can you fix this before implementing a mobile version, as I am not able to even slightly control any page with my css, for some reason.

**Comment by AetherPrior** [comment]
@HarshvardhanJha1 did you manage to figure this one out?

**Comment by AetherPrior** [comment]
@VikramjeetD I think this is fixed
